name: card_stack_widget
description: Card stack widget for Flutter
version: 0.0.1
homepage: www.federicoviceconti.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: