name: card_stack_widget
description: A vertical dismissible and customizable stack of cards for Flutter applications
version: 0.0.6
homepage: https://www.federicoviceconti.com
repository: https://github.com/federicoviceconti/card_stack_widget

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter: